name: Continous Integration (Angular)
on:
  push:
    paths:
      - '**.ts'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14.x

      - name: Setup
        working-directory: ./angular
        run: npm ci

      - name: Test
        working-directory: ./angular
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
